[versions]
agp = "8.13.1"
splash = "1.2.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
coroutines = "1.10.2"
serialization = "1.9.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
hiltNavigation = "1.3.0"
navigation = "2.9.6"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
appcompat = "1.7.1"
material = "1.13.0"
retrofit = "3.0.0"
room = "2.8.4"
hilt = "2.57.2"
devtools = "2.2.21-2.0.4"
paging = "3.3.6"
coil = "3.3.0"
result = "2.23.0.0"
log = "4.11.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Kotlin
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }

# Architecture Components
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-compose-material = { group = "androidx.compose.material", name = "material-icons-extended"}
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Android X: Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }

# DI
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Pagination
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-test = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# Network
retrofit-base = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
retrofit-log = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "log"}

# Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Image Loading
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Result
result4k-bom = { group = "dev.forkhandles", name = "forkhandles-bom", version.ref = "result" }
result4k = { group = "dev.forkhandles", name = "result4k", version.ref="result"}

[bundles]
room = [ "room-runtime", "room-ktx", "room-paging" ]
retrofit = [ "retrofit-base", "retrofit-gson-converter", "retrofit-log" ]
paging = [ "paging-runtime" ]
compose = [ "androidx-compose-ui", "androidx-compose-ui-graphics", "androidx-compose-material3", "androidx-compose-material", "androidx-activity-compose", "androidx-compose-ui-tooling-preview", "paging-compose" ]
compose-debug = ["androidx-compose-ui-tooling", "androidx-compose-ui-test-manifest"]
compose-test = ["androidx-compose-ui-test-junit4", "androidx-compose-ui-test-manifest"]
navigation = ["androidx-navigation-compose", "androidx-hilt-navigation-compose"]
lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-runtime-compose", "androidx-lifecycle-viewmodel-compose"]
coil = ["coil", "coil-network"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-parcelize= { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
android-library = { id = "com.android.library", version.ref = "agp" }
devtools = { id = "com.google.devtools.ksp", version.ref = "devtools" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }



