[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
coroutines = "1.10.2"
serialization = "1.9.0"
junit = "6.0.1"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
hiltNavigation = "1.3.0"
navigation = "2.9.6"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
appcompat = "1.7.1"
material = "1.13.0"
retrofit = "3.0.0"
room = "2.8.4"
hilt = "2.57.2"
devtools = "2.2.21-2.0.4"
paging = "3.3.6"
coil = "3.3.0"
result = "2.23.0.0"
log = "5.3.2"
mockk = "1.14.6"
turbine = "1.2.1"
truth = "1.4.5"
android-junit5 = "1.14.0.0"

[libraries]

# Kotlin
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = {  group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# Core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# Unit Testing 101
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
truth = { group = "com.google.truth", name = "truth", version.ref="truth" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk"}
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Instrumented Testing 101
androidx-test-core = { group = "androidx.test", name = "core", version = "1.6.1" }
androidx-test-runner = { group = "androidx.test", name = "runner", version = "1.6.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

# Architecture Components
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3"}
compose-material = { group = "androidx.compose.material", name = "material-icons-extended"}
compose-ui = { group = "androidx.compose.ui", name = "ui"}
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling"}
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Android X: Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigation" }

# DI
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Pagination
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "paging" }

# Network
retrofit-base = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson-converter = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit"}
retrofit-log = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "log"}

# Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# Image Loading
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Result
result4k-bom = { group = "dev.forkhandles", name = "forkhandles-bom", version.ref = "result" }
result4k = { group = "dev.forkhandles", name = "result4k", version.ref="result"}

[bundles]
room = [ "room-runtime", "room-ktx", "room-paging" ]
retrofit = [ "retrofit-base", "retrofit-gson-converter", "retrofit-log" ]
paging = [ "paging-runtime" ]
compose = [ "compose-ui", "compose-ui-graphics", "compose-material3", "compose-material", "activity-compose", "compose-ui-tooling-preview", "paging-compose" ]
compose-debug = ["compose-ui-tooling", "compose-ui-test-manifest"]
compose-test = ["compose-ui-test-junit4", "compose-ui-test-manifest"]
navigation = ["navigation-compose", "hilt-navigation-compose"]
lifecycle = ["lifecycle-runtime-ktx", "lifecycle-runtime-compose", "lifecycle-viewmodel-compose"]
coil = ["coil", "coil-network"]

testing = [ "junit", "androidx-junit", "truth", "mockk", "turbine", "kotlin-test", "kotlin-coroutines-test"]
testing-instr = [ "kotlin-test", "androidx-test-core", "androidx-test-runner", "androidx-junit", "room-test", "kotlin-coroutines-test", "turbine" ]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
kotlin-parcelize= { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin"}
android-library = { id = "com.android.library", version.ref = "agp" }
devtools = { id = "com.google.devtools.ksp", version.ref = "devtools" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }




